- name: Install php-fpm and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-mcrypt
    - php-mysql
    - php-curl
    - php-pear
    - php-gd
    - php-mbstring
    - curl
    - postfix
    - vim
    - npm
    - git
  tags:
    - packages

#- name: Enabled mcrypt
#  command: php5enmod mcrypt
#  notify:
#    - restart php7.0-fpm

- name: Install xdebug
  apt:
    name: php-xdebug
    state: present
  when: fpm_debug

- name: Create xdebug log file
  file:
    state: touch
    path: /var/log/xdebug/xdebug
    owner: www-data
    group: www-data
    mode: 0777
  when: fpm_debug


- name: Configure xdebug
  template:
    src: xdebug.ini
    dest: "{{fpm_php_config_dir}}/mods-available/xdebug.ini"
  when: fpm_debug
  notify:
    - restart php7.0-fpm
    - restart nginx

- name: Disable default pool
  # Move the default pool if they haven't be moved.
  command: >
    mv
    {{ fpm_pool_dir }}/www.conf
    {{ fpm_pool_dir }}/www.disabled
    creates={{ fpm_pool_dir }}/www.disabled
  notify: restart php7.0-fpm

- name: Copy php-fpm configuration
  template:
    src: web.conf
    dest: "{{ fpm_pool }}"
  notify: restart php7.0-fpm

- name: Change upload max file size
  lineinfile:
    name: "{{fpm_php_config_dir}}/fpm/php.ini"
    regexp: 'upload_max_filesize'
    line: 'upload_max_filesize = {{ fpm_upload_max_filesize }}M'

- name: Change max post size
  lineinfile:
    name: "{{fpm_php_config_dir}}/fpm/php.ini"
    regexp: 'post_max_size'
    line: 'post_max_size = {{ fpm_max_body_size }}M'
  notify:
    - restart php7.0-fpm
    - restart nginx
  tags:
    - config
    - php-fpm

- name: Change upload max file size
  lineinfile:
    name: "{{fpm_php_config_dir}}/fpm/php.ini"
    regexp: 'max_execution_time'
    line: 'max_execution_time = {{ fpm_max_execution_time }}'

- name: Set permissions to /var/www
  file:
    state: directory
    path: /var/www
    owner: www-data
    group: www-data
    mode: 0754

- name: Increace realpath cache size of PHP
  lineinfile:
    name: "{{ fpm_init_pathname }}"
    regexp: "realpath_cache_size"
    line: "realpath_cache_size={{ fpm_realpath_cache_size }}K"
  notify:
    - restart php7.0-fpm
  tags:
    - php-fpm
    - php-config

- name: Increace realpath cache ttl of PHP
  lineinfile:
    name: "{{ fpm_init_pathname }}"
    regexp: "realpath_cache_ttl"
    line: "realpath_cache_ttl={{ fpm_realpath_cache_ttl }}"
  notify:
    - php7.0-fpm
    - restart php7.0-fpm
  tags:
    - php-fpm
    - php-config

- name: Force restart of FPM
  service:
    name: php7.0-fpm
    state: restarted
