- name: Install php-fpm and dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-cli
    - php5-fpm
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php-pear
    - php5-gd
    - php-apc
    - curl
    - postfix
    - vim
    - npm
    - git
  tags:
    - packages

- name: Enabled mcrypt
  command: php5enmod mcrypt
  notify:
    - restart php5-fpm

- name: Install xdebug
  apt:
    name: php5-xdebug
    state: present
  when: fpm_debug

- name: Configure xdebug
  copy:
    src: xdebug.ini
    dest: /etc/php5/mods-available/xdebug.ini
  when: fpm_debug
  notify:
    - restart php5-fpm
    - restart nginx

- name: Fix xdebug extension
  shell: echo zend_extension="$(find /usr/lib/php5/ -name xdebug.so)" >> /etc/php5/mods-available/xdebug.ini
  when: fpm_debug

- name: Disable default pool
  # Move the default pool if they haven't be moved.
  command: >
    mv
    {{ fpm_pool_dir }}/www.conf
    {{ fpm_pool_dir }}/www.disabled
    creates={{ fpm_pool_dir }}/www.disabled
  notify: restart php5-fpm

- name: Copy php-fpm configuration
  template:
    src: web.conf
    dest: "{{ fpm_pool }}"
  notify: restart php5-fpm

- name: Change upload max file size
  lineinfile:
    name: /etc/php5/fpm/php.ini
    regexp: 'upload_max_filesize'
    line: 'upload_max_filesize = {{ fpm_upload_max_filesize }}M'

- name: Change max post size
  lineinfile:
    name: /etc/php5/fpm/php.ini
    regexp: 'post_max_size'
    line: 'post_max_size = {{ fpm_max_body_size }}M'
  notify:
    - restart php5-fpm
    - restart nginx
  tags:
    - config
    - php-fpm

- name: Set permissions to /var/www
  file:
    state: directory
    path: /var/www
    owner: www-data
    group: www-data
    mode: 0754

- name: Increace realpath cache size of PHP
  lineinfile:
    name: "{{ fpm_init_pathname }}"
    regexp: "realpath_cache_size"
    line: "realpath_cache_size={{ fpm_realpath_cache_size }}K"
  notify:
    - restart php5-fpm
  tags:
    - php-fpm
    - php-config

- name: Increace realpath cache ttl of PHP
  lineinfile:
    name: "{{ fpm_init_pathname }}"
    regexp: "realpath_cache_ttl"
    line: "realpath_cache_ttl={{ fpm_realpath_cache_ttl }}"
  notify:
    - restart php5-fpm
  tags:
    - php-fpm
    - php-config

- name: Force restart of FPM
  service:
    name: php5-fpm
    state: restarted
