name: elpalaciodehierro
domain: elpalaciodehierro.dev
full_domain: www.elpalaciodehierro.dev
local_path: ../palacioviejos

############################
# Virtual machine settings
###########################
vm_ip: 192.168.1.11
vm_cpus: 2
vm_memory: 4096