domain: proyect-x.dev
full_domain: www.proyect-x.dev
local_path: ../proyect-x

vm:
  box: "ubuntu14.04-amd64"
  name: proyect-x
  ip: 192.168.1.11
  cpus: 2
  memory: 4096

ansible:
  raw_arguments: [-vvvv]