- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server-5.6
  tags:
    - packages
    - mysql

- name: "Create MySql DBs {{ mysql_db_name }}"
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
  tags:
    - mysql
    - mysql_config
    - mysql_create_db
    - project

- name: "Create user to {{ mysql_db_name }}"
  mysql_user:
    name: "{{ mysql_new_user }}"
    password: "{{ mysql_new_user_password }}"
    priv: '*.*:ALL'
    state: present
  tags:
    - mysql
    - mysql_config
    - mysql_create_user
    - project