- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server-5.6
  tags:
    - packages
    - mysql

- name: "Create MySql DBs {{ mysql_db_name }}"
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
  tags:
    - mysql
    - mysql_config
    - mysql_create_db

- name: "Create user to {{ mysql_db_name }}"
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: '*.*:ALL'
    state: present
    host: "%"
  with_items: mysql_new_users
  notify:
    - restart mysql
  tags:
    - mysql
    - mysql_config
    - mysql_create_user

- name: Enable remoted connections
  lineinfile:
    name: /etc/mysql/my.cnf
    regexp: "^(b|#b)ind-address"
    line: "bind-address    = 0.0.0.0"
  tags:
    - mysql
    - mysql_config
  notify:
    - restart mysql

- name: Create slow query file
  file:
    state: present
    path: /var/log/mysql/log-slow-queries.log
  when: debug

- name: Enable slow queries
  lineinfile:
    name: /etc/mysql/my.cnf
    regexp: "log-slow-queries="
    line: "log-slow-queries=/var/log/mysql/log-slow-queries.log"
  when: debug

- name: Enable slow queries
  lineinfile:
    name: /etc/mysql/my.cnf
    regexp: "log-slow-queries="
    line: "set-variable=long_query_time= 5"
  when: debug
