- name: Install dev tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - nodejs
      - npm
      - ruby
      - libnotify-bin

#- name: Fixed nodejs in Ubuntu
#  file:
#    state: link
#    src: /usr/bin/nodejs
#    dest: /usr/bin/node

- name: Install npm packages
  shell: "npm install"
  args:
    chdir: "/var/www/{{domain}}"

- name: Create gulp alias
  shell: echo 'alias gulp="./node_modules/gulp/bin/gulp.js"' > .zshrc
  args:
    chdir: /home/vagrant

- name: Create base directory
  file:
    state: directory
    path: /var/www
    owner: vagrant
    group: vagrant
    mode: 0754

- name: Change nginx user
  lineinfile:
    name: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user vagrant;'

- name: Change php-fpm owner
  lineinfile:
    name: "{{ vagrant_fpm_pool }}"
    regexp: '^listen\.owner.*www-data'
    line: 'listen.owner = vagrant'

- name: Change php-fpm group
  lineinfile:
    name: /etc/php/7.0/fpm/pool.d/www.conf
    regexp: '^listen\.group.*www-data'
    line: 'listen.group = vagrant'

- name: Change php-fpm socket permissions
  file:
    path: "{{ vagrant_fpm_socket }}"
    owner: vagrant
    group: vagrant
  tags:
    - config

- name: Add vagrant user to www-data group
  user:
    name: vagrant
    groups: www-data

